# Generated by Django 4.2.3 on 2023-09-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=14),
        ),
    ]
