# Generated by Django 4.2.3 on 2023-09-07 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0002_alter_user_age_alter_user_height_alter_user_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='height',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='weight',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='PProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(choices=[('0', 'Select Year'), ('8-15', 'children'), ('15-31', 'young age'), ('32-55', 'middle age'), ('55-above', 'post middle age')], default='0', max_length=9)),
                ('per', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('subjects', models.CharField(max_length=50)),
                ('expr', models.IntegerField()),
                ('designation', models.CharField(max_length=50)),
                ('dch', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
