# Generated by Django 4.2.3 on 2023-09-07 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0003_alter_user_age_alter_user_height_alter_user_weight_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pprofile',
            name='bmi',
            field=models.CharField(choices=[('<25', 'underweight'), ('>25', 'overweight'), ('=25', 'Healthyweight')], default='0', max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='pfimg',
            field=models.ImageField(default='demoprofile.png', upload_to='Profiles/'),
        ),
    ]
