# Generated by Django 4.2.3 on 2023-09-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0005_dietsuggestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReqUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=50)),
                ('reqdate', models.DateField(auto_now=True)),
                ('aprdate', models.DateField(auto_now=True)),
                ('stsckey', models.CharField(choices=[('0', 'Request'), ('1', 'Done'), ('2', 'Accepted'), ('3', 'Rejected')], default='0', max_length=5)),
                ('stsstatus', models.CharField(max_length=10)),
                ('dt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dietapp.dietsuggestion')),
                ('pp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
