# Generated by Django 4.2.3 on 2024-08-13 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dietapp', '0006_requsers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requsers',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='requsers',
            name='pp',
        ),
        migrations.RemoveField(
            model_name='requsers',
            name='stsstatus',
        ),
        migrations.AddField(
            model_name='requsers',
            name='ststatus',
            field=models.CharField(choices=[('0', 'Request'), ('1', 'Done'), ('2', 'Accepted'), ('3', 'Rejected')], default='0', max_length=5),
        ),
        migrations.CreateModel(
            name='DietRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_details', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dietician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_received', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests_made', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
